[fr]
contentDir = "content/fr"
disabled = false
languageCode = "fr-FR"
languageDirection = "ltr"
languageName = "French"
title = "The Cloud Optimist"
weight = 1

[fr.params]
subtitle = "The Cloud Optimist"

[fr.params.sidebar]
subtitle = "Un blog autour des sujets Cloud & DevOps."

[fr.params.dateFormat]
published = "02 Jan 2006"
lastUpdated = "02 Jan 2006, 15:04 CET"

[fr.params.comments.giscus]
lang = "fr"

[[fr.menu.main]]
identifier = "home"
name = "Accueil"
url = "/fr"
weight = 1

[fr.menu.main.params]
icon = "home"
newtab = false

[[fr.menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/antoinedelia/"

[fr.menu.social.params]
icon = "brand-github"

[[fr.menu.social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://linkedin.com/in/antoinedelia"

[fr.menu.social.params]
icon = "brand-linkedin"

[[fr.menu.social]]
identifier = "stackoverflow"
name = "Stack Overflow"
url = "https://stackoverflow.com/users/4141606/antoine-delia?tab=profile"

[fr.menu.social.params]
icon = "brand-stackoverflow"

[en]
contentDir = "content/en"
disabled = false
languageCode = "en-US"
languageDirection = "ltr"
languageName = "English"
title = "The Cloud Optimist"
weight = 2

[en.params]
subtitle = "The Cloud Optimist"

[en.params.sidebar]
subtitle = "A blog about Cloud & DevOps topics."

[en.params.dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 CET"

[en.menu]
[[en.menu.main]]
identifier = "home"
name = "Home"
url = "/en"
weight = 1

[en.menu.main.params]
icon = "home"
newtab = false

[[en.menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/antoinedelia/"

[en.menu.social.params]
icon = "brand-github"

[[en.menu.social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://linkedin.com/in/antoinedelia"

[en.menu.social.params]
icon = "brand-linkedin"

[[en.menu.social]]
identifier = "stackoverflow"
name = "Stack Overflow"
url = "https://stackoverflow.com/users/4141606/antoine-delia?tab=profile"

[en.menu.social.params]
icon = "brand-stackoverflow"
