# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["posts"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.ico"

[footer]
since = 2022
customText = ""

[sidebar]
emoji = "☁️"
subtitle = "A blog about Cloud & DevOps topics."

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[article]
headingAnchor = true
math = false
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "giscus"

[comments.giscus]
repo = "antoinedelia/cloud-optimist"
repoID = "R_kgDOHWH-Zg"
category = "Comments"
categoryID = "DIC_kwDOHWH-Zs4CoHBh"
mapping = "pathname"
strict = 0
reactionsEnabled = 1
emitMetadata = 1
inputPosition = "top"
lightTheme = ""
darkTheme = ""
# Commenting this will use the default language
# lang = "en"
